export const subscriptionPlans = [
    {
        name: "Basic Plan",
        price: 9.99,
        duration: 1,
        description: "Best for beginners",
        isRecommended: false,
        features: [
            "Daily Pick 3 Predictions",
            "Access to 1 State",
            "Draw History (Last 30 Days)",
            "Email Support",
            "Basic Hit Tracker",
        ],
    },
    {
        name: "Premium Plan",
        price: 19.99,
        duration: 1,
        description: "Most popular choice",
        isRecommended: true,
        features: [
            "Daily Pick 3 Predictions",
            "Access to All States",
            "Full Draw History",
            "Priority Email Support",
            "Advanced Hit Tracker",
            "Weekly Performance Reports",
            "Early Access to New Features",
        ],
    },
    {
        name: "VIP Plan",
        price: 39.99,
        duration: 1,
        description: "For power users",
        isRecommended: false,
        features: [
            "Everything in Premium",
            "Real-time Predictions",
            "24/7 Priority Support",
            "Custom Prediction Requests",
            "Monthly Strategy Consultation",
            "Exclusive VIP Community Access",
            "Money-Back Guarantee",
        ],
    },
    {
        name: "Enterprise Plan",
        price: 79.99,
        duration: 1,
        description: "Custom solutions for large teams (Coming Soon)",
        isRecommended: false,
        isActive: false,
        features: [
            "Unlimited State Access",
            "Dedicated Account Manager",
            "Custom Prediction Algorithms",
            "Team & Multi-User Access",
            "Advanced Analytics Dashboard",
            "API Access",
            "Custom Integrations",
        ],
    }
];
